In [1]:
import imdb

In [2]:
import numpy as np

In [4]:
%time train = imdb.IMDBdata("data/aclImdb/train")

CPU times: user 20.6 s, sys: 2.93 s, total: 23.5 s
Wall time: 32.3 s


In [5]:
w = np.random.random(train.X.shape[1])
print w

[0.89761521 0.04113505 0.34914902 ... 0.47168753 0.0151268  0.62381109]


In [6]:
train.X.shape

(25000, 252193)

In [7]:
%%time
train.X[0,:].dot(w)

CPU times: user 487 µs, sys: 586 µs, total: 1.07 ms
Wall time: 2.32 ms


array([139.7522802])

In [8]:
%%time
sum = 0
for i in range(train.X.shape[1]):
    sum += train.X[0,i] * w[i]
print sum

139.75228019873958
CPU times: user 11.5 s, sys: 58.8 ms, total: 11.6 s
Wall time: 11.8 s


In [9]:
train.Y

array([-1.,  1., -1., ...,  1.,  1.,  1.])

In [10]:
word_counts = np.array(train.X[train.Y == -1,:].sum(axis=0)).flatten()
word_counts

array([21141, 77895, 17370, ...,     1,     1,     1])

In [11]:
sorted_words = list(reversed(np.argsort(word_counts)))
sorted_words[0:10]

[28, 1, 110, 11, 66, 21, 195, 180, 15, 3]

In [12]:
sorted_words[0]

28

In [13]:
train.vocab.GetWord(sorted_words[0])

'the'

In [14]:
[train.vocab.GetWord(sorted_words[x]) for x in range(10)]

['the', 'a', 'and', 'of', 'to', 'is', 'in', 'i', 'this', 'that']

In [15]:
x = range(10)

In [16]:
x


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
[a + 1 for a in x]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]